#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jul 23 10:42:17 2024

@author: charmainechia
"""


def sort_list(lst):
    lst.sort()
    return lst


def dict_update(d, keyval):
    d.update(keyval)
    return d


# data folder
data_folder = '../ajino-analytics-data/'
# figure fodler
figure_folder = f'{data_folder}figures/'

sampling_rawdata_dict = {
    0: {'fname': '240402_20RP06-19_data for Astar_4conditions_v2.xlsx', 'skiprows': [2, 2, 2, 2, 2, None, 2, 1], 'usecols': ['B:CA', 'B:DR', 'B:BE', 'B:BE', 'B:AZ', None, 'B:AI', 'A:F'], 'cqa_startcol': [6, 6, 6, 6, 6, None, 2, 1], },
    1: {'fname': '240906_22DX05-12_media combination_AJI-Astar_v2.xlsx', 'skiprows': [2, 2, 2, 2, 2, 2, 2, 2], 'usecols': ['B:BH', 'B:FN', 'B:CA', 'B:CA', 'B:BT', 'B:AK', 'B:GM', 'B:J'], 'cqa_startcol': [8, 8, 8, 8, 8, 8, 2, 1], },
    2: {'fname': '240906_22DX05-12_process combination_AJI-Astar_v3.xlsx', 'skiprows': [2, 2, 2, 2, 2, 2, 2, 2], 'usecols': ['B:BF', 'B:FN', 'B:CA', 'B:CA', 'B:BT', 'B:AK', 'B:GM', 'B:D'], 'cqa_startcol': [8, 8, 8, 8, 8, 8, 2, 1], },
}

media_rawdata_dict = {
    0: {'fname': '240402_20RP06-19_data for Astar_4conditions_v2.xlsx', 'skiprows': 1, 'usecols': 'A:F', 'cqa_startcol': 1, },
    1: {'fname': '240906_22DX05-12_media combination_AJI-Astar_v2.xlsx', 'skiprows': 2, 'usecols': 'B:J', 'cqa_startcol': 1, },
    2: {'fname': '240906_22DX05-12_process combination_AJI-Astar_v3.xlsx', 'skiprows': 2, 'usecols': 'B:D', 'cqa_startcol': 1, },
}

sampling_days = {
    0: [0, 3, 5, 7, 9, 11, 13, 14],
    1: [0, 3, 5, 7, 9, 11, 14],
    2: [0, 3, 5, 7, 9, 11, 14],
}

sampling_days_itpl = {
    0: [0, 1, 2, 3, 4, 5, 6, 7, 9, 11, 13, 14],
    1: [0, 3, 5, 7, 9, 11, 14],
    2: [0, 3, 5, 7, 9, 11, 14],
}

vol_df_exp_cols = [
    'Day',
    'event',
    'time (d)',
    'time (m)',
    'vessel volume (mL)',
    'feed (mL)',
    'glucose (mL)'
]

overall_glyco_cqas = {
    'mannosylation': ['Man5'],
    'fucosylation': ['G0F', 'G1Fa', 'G1Fb', 'G2F'],
    'galactosylation': ['G1', 'G1Fa', 'G1Fb', 'G2', 'G2F']
}

var_dict_all = {
    'inputs': [
        'Basal medium',
        'Feed medium',
        'DO',
        'pH',
        'feed %',
        'feed day',
        'feed vol',
    ],
    'VCD, VIA, Titer, metabolites': [
        'VCD (E6 cells/mL)',
        'Viability (%)',
        'Titer (mg/L)',
        'Osmolarity (mOsm/kg)',
        'Glucose (g/L)',
        'Lac (g/L)',
        'NH4+ (mM)'
    ],
    'AA': [
        'Ala',
        'Arg',
        'Asn',
        'Asp',
        'Gln',
        'Glu',
        'Gly',
        'Gly-Tyr',
        'His',
        'HyPro',
        'Ile',
        'Leu',
        'Lys',
        'Met',
        'Orn',
        'Phe',
        'Pro',
        'Ser',
        'Tau',
        'Thr',
        'Trp',
        'Tyr',
        'Val'
    ],
    'VT': [
        'Choline',
        'Thiamin',
        'Pyridoxal',
        'Pyridoxine',
        'Nicotinamide',
        'Pantothenic  acid',
        'Folic acid',
        'Cyanocobalamin',
        'Riboflavin',
        'Biotin'
    ],
    'MT': [
        'Na',
        'Mg',
        'P',
        'K',
        'Ca',
        'Fe',
        'Co',
        'Cu',
        'Zn',
        'Mn'
    ],
    'Glyco': [
        'Man5',
        'G0',
        'G0F',
        'G1',
        'G1Fa',
        'G1Fb',
        'G2',
        'G2F',
        'Other'
    ],
    'Nuc, Amine': [
        'Ethanolamine',
        'Putrescine',
        'Uridine',
        'Adenosine'
    ],
    'media_components': [
        'Ala',
        'Arg',
        'Asn',
        'Asp',
        'Glu',
        'Gly',
        'Gly-Tyr',
        'His',
        'HyPro',
        'Ile',
        'Leu',
        'Lys',
        'Met',
        'Orn',
        'Phe',
        'Pro',
        'Ser',
        'Tau',
        'Thr',
        'Trp',
        'Tyr',
        'Val',
        'Choline',
        'Thiamin',
        'Pyridoxal',
        'Pyridoxine',
        'Nicotinamide',
        'Pantothenic  acid',
        'Folic acid',
        'Cyanocobalamin',
        'Riboflavin',
        'Biotin',
        'Ethanolamine',
        'Uridine',
        'Na',
        'Mg',
        'P',
        'K',
        'Ca',
        'Fe',
        'Co',
        'Cu',
        'Zn',
        'Mn',
        'D-glucose'
    ]
}

nutrients_dict_all = {
    'AA': [
        'Ala',
        'Arg',
        'Asn',
        'Asp',
        'Gln',
        'Glu',
        'Gly',
        'Gly-Tyr',
        'His',
        'HyPro',
        'Ile',
        'Leu',
        'Lys',
        'Met',
        'Orn',
        'Phe',
        'Pro',
        'Ser',
        'Tau',
        'Thr',
        'Trp',
        'Tyr',
        'Val'
    ],
    'VT': [
        'Biotin',
        'Choline',
        'Cyanocobalamin',
        'Folic acid',
        'Nicotinamide',
        'Pantothenic  acid',
        'Pyridoxal',
        'Pyridoxine',
        'Riboflavin',
        'Thiamin'
    ],
    'MT': [
        'Ca',
        'Co',
        'Cu',
        'Fe',
        'K',
        'Mg',
        'Mn',
        'Na',
        'P',
        'Zn'
    ],
    'Nuc, Amine': [
        'Adenosine',
        'Ethanolamine',
        'Putrescine',
        'Uridine'],
    'other': [
        'D-glucose',
        'Glucose (g/L)'
    ]
}

nutrients_list_all = [
    'Ala',
    'Arg',
    'Asn',
    'Asp',
    'Gln',
    'Glu',
    'Gly',
    'Gly-Tyr',
    'His',
    'HyPro',
    'Ile',
    'Leu',
    'Lys',
    'Met',
    'Orn',
    'Phe',
    'Pro',
    'Ser',
    'Tau',
    'Thr',
    'Trp',
    'Tyr',
    'Val',
    'Biotin',
    'Choline',
    'Cyanocobalamin',
    'Folic acid',
    'Nicotinamide',
    'Pantothenic  acid',
    'Pyridoxal',
    'Pyridoxine',
    'Riboflavin',
    'Thiamin',
    'Ca',
    'Co',
    'Cu',
    'Fe',
    'K',
    'Mg',
    'Mn',
    'Na',
    'P',
    'Zn',
    'Adenosine',
    'Ethanolamine',
    'Putrescine',
    'Uridine',
    'D-glucose',
    'Glucose (g/L)'
]

nutrients_calculated_list = [
    'Arg',
    'Asn',
    'Asp',
    'Glu',
    'Gly-Tyr',
    'His',
    'Ile',
    'Leu',
    'Lys',
    'Met',
    'Phe',
    'Pro',
    'Ser',
    'Tau',
    'Thr',
    'Trp',
    'Val',
    'Choline',
    'Thiamin',
    'Nicotinamide',
    'Pantothenic  acid',
    'Folic acid',
    'Cyanocobalamin',
    'Riboflavin',
    'Biotin',
    'Na',
    'Mg',
    'P',
    'K',
    'Ca',
    'Fe',
    'Co',
    'Cu',
    'Zn',
    'Mn',
    # 'Glucose (g/L)',
    'Pyridoxine',
    'Tyr',
    'Uridine',
    'Ala',
    'Ethanolamine'
]
# %% X % Y DATASET VARIABLES
xvar_list_dict_prefilt = {
    0: [
        'Ala_basal',
        'Arg_basal',
        'Asn_basal',
        'Asp_basal',
        'Glu_basal',
        'Gly_basal',
        'Gly-Tyr_basal',
        'His_basal',
        'HyPro_basal',
        'Ile_basal',
        'Leu_basal',
        'Lys_basal',
        'Met_basal',
        'Orn_basal',
        'Phe_basal',
        'Pro_basal',
        'Ser_basal',
        'Tau_basal',
        'Thr_basal',
        'Trp_basal',
        'Tyr_basal',
        'Val_basal',
        'Choline_basal',
        'Thiamin_basal',
        'Pyridoxal_basal',
        'Pyridoxine_basal',
        'Nicotinamide_basal',
        'Pantothenic  acid_basal',
        'Folic acid_basal',
        'Cyanocobalamin_basal',
        'Riboflavin_basal',
        'Biotin_basal',
        'Ethanolamine_basal',
        'Uridine_basal',
        'Na_basal',
        'Mg_basal',
        'P_basal',
        'K_basal',
        'Ca_basal',
        'Fe_basal',
        'Co_basal',
        'Cu_basal',
        'Zn_basal',
        'Mn_basal',
        'D-glucose_basal',
        'Ala_feed',
        'Arg_feed',
        'Asn_feed',
        'Asp_feed',
        'Glu_feed',
        'Gly_feed',
        'Gly-Tyr_feed',
        'His_feed',
        'HyPro_feed',
        'Ile_feed',
        'Leu_feed',
        'Lys_feed',
        'Met_feed',
        'Orn_feed',
        'Phe_feed',
        'Pro_feed',
        'Ser_feed',
        'Tau_feed',
        'Thr_feed',
        'Trp_feed',
        'Tyr_feed',
        'Val_feed',
        'Choline_feed',
        'Thiamin_feed',
        'Pyridoxal_feed',
        'Pyridoxine_feed',
        'Nicotinamide_feed',
        'Pantothenic  acid_feed',
        'Folic acid_feed',
        'Cyanocobalamin_feed',
        'Riboflavin_feed',
        'Biotin_feed',
        'Ethanolamine_feed',
        'Uridine_feed',
        'Na_feed',
        'Mg_feed',
        'P_feed',
        'K_feed',
        'Ca_feed',
        'Fe_feed',
        'Co_feed',
        'Cu_feed',
        'Zn_feed',
        'Mn_feed',
        'D-glucose_feed',
        'DO',
        'pH',
        'feed %',
        'feed vol'
    ],

    1: [
        'Ala_basal',
        'Arg_basal',
        'Asn_basal',
        'Asp_basal',
        'Glu_basal',
        'Gly_basal',
        'Gly-Tyr_basal',
        'His_basal',
        'HyPro_basal',
        'Ile_basal',
        'Leu_basal',
        'Lys_basal',
        'Met_basal',
        'Orn_basal',
        'Phe_basal',
        'Pro_basal',
        'Ser_basal',
        'Tau_basal',
        'Thr_basal',
        'Trp_basal',
        'Tyr_basal',
        'Val_basal',
        'Choline_basal',
        'Thiamin_basal',
        'Pyridoxal_basal',
        'Pyridoxine_basal',
        'Nicotinamide_basal',
        'Pantothenic  acid_basal',
        'Folic acid_basal',
        'Cyanocobalamin_basal',
        'Riboflavin_basal',
        'Biotin_basal',
        'Ethanolamine_basal',
        'Uridine_basal',
        'Na_basal',
        'Mg_basal',
        'P_basal',
        'K_basal',
        'Ca_basal',
        'Fe_basal',
        'Co_basal',
        'Cu_basal',
        'Zn_basal',
        'Mn_basal',
        'D-glucose_basal',
        'Ala_feed',
        'Arg_feed',
        'Asn_feed',
        'Asp_feed',
        'Glu_feed',
        'Gly_feed',
        'Gly-Tyr_feed',
        'His_feed',
        'HyPro_feed',
        'Ile_feed',
        'Leu_feed',
        'Lys_feed',
        'Met_feed',
        'Orn_feed',
        'Phe_feed',
        'Pro_feed',
        'Ser_feed',
        'Tau_feed',
        'Thr_feed',
        'Trp_feed',
        'Tyr_feed',
        'Val_feed',
        'Choline_feed',
        'Thiamin_feed',
        'Pyridoxal_feed',
        'Pyridoxine_feed',
        'Nicotinamide_feed',
        'Pantothenic  acid_feed',
        'Folic acid_feed',
        'Cyanocobalamin_feed',
        'Riboflavin_feed',
        'Biotin_feed',
        'Ethanolamine_feed',
        'Uridine_feed',
        'Na_feed',
        'Mg_feed',
        'P_feed',
        'K_feed',
        'Ca_feed',
        'Fe_feed',
        'Co_feed',
        'Cu_feed',
        'Zn_feed',
        'Mn_feed',
        'D-glucose_feed',
        'DO',
        'pH',
        'feed vol'
    ],

    2: [
        'Ala_basal',
        'Arg_basal',
        'Asn_basal',
        'Asp_basal',
        'Glu_basal',
        'Gly_basal',
        'Gly-Tyr_basal',
        'His_basal',
        'HyPro_basal',
        'Ile_basal',
        'Leu_basal',
        'Lys_basal',
        'Met_basal',
        'Orn_basal',
        'Phe_basal',
        'Pro_basal',
        'Ser_basal',
        'Tau_basal',
        'Thr_basal',
        'Trp_basal',
        'Tyr_basal',
        'Val_basal',
        'Choline_basal',
        'Thiamin_basal',
        'Pyridoxal_basal',
        'Pyridoxine_basal',
        'Nicotinamide_basal',
        'Pantothenic  acid_basal',
        'Folic acid_basal',
        'Cyanocobalamin_basal',
        'Riboflavin_basal',
        'Biotin_basal',
        'Ethanolamine_basal',
        'Uridine_basal',
        'Na_basal',
        'Mg_basal',
        'P_basal',
        'K_basal',
        'Ca_basal',
        'Fe_basal',
        'Co_basal',
        'Cu_basal',
        'Zn_basal',
        'Mn_basal',
        'D-glucose_basal',
        'Ala_feed',
        'Arg_feed',
        'Asn_feed',
        'Asp_feed',
        'Glu_feed',
        'Gly_feed',
        'Gly-Tyr_feed',
        'His_feed',
        'HyPro_feed',
        'Ile_feed',
        'Leu_feed',
        'Lys_feed',
        'Met_feed',
        'Orn_feed',
        'Phe_feed',
        'Pro_feed',
        'Ser_feed',
        'Tau_feed',
        'Thr_feed',
        'Trp_feed',
        'Tyr_feed',
        'Val_feed',
        'Choline_feed',
        'Thiamin_feed',
        'Pyridoxal_feed',
        'Pyridoxine_feed',
        'Nicotinamide_feed',
        'Pantothenic  acid_feed',
        'Folic acid_feed',
        'Cyanocobalamin_feed',
        'Riboflavin_feed',
        'Biotin_feed',
        'Ethanolamine_feed',
        'Uridine_feed',
        'Na_feed',
        'Mg_feed',
        'P_feed',
        'K_feed',
        'Ca_feed',
        'Fe_feed',
        'Co_feed',
        'Cu_feed',
        'Zn_feed',
        'Mn_feed',
        'D-glucose_feed',
        'DO',
        'pH',
        'feed %'
    ],

    3: [
        'Adenosine_0',
        'Ala_0',
        'Arg_0',
        'Asn_0',
        'Asp_0',
        'Biotin_0',
        'Ca_0',
        'Choline_0',
        'Co_0',
        'Cu_0',
        'Cyanocobalamin_0',
        'Ethanolamine_0',
        'Fe_0',
        'Folic acid_0',
        'Gln_0',
        'Glu_0',
        'Glucose (g/L)_0',
        'Gly-Tyr_0',
        'Gly_0',
        'His_0',
        'HyPro_0',
        'Ile_0',
        'K_0',
        'Leu_0',
        'Lys_0',
        'Met_0',
        'Mg_0',
        'Mn_0',
        'Na_0',
        'Nicotinamide_0',
        'Orn_0',
        'P_0',
        'Pantothenic  acid_0',
        'Phe_0',
        'Pro_0',
        'Putrescine_0',
        'Pyridoxal_0',
        'Pyridoxine_0',
        'Riboflavin_0',
        'Ser_0',
        'Tau_0',
        'Thiamin_0',
        'Thr_0',
        'Trp_0',
        'Tyr_0',
        'Uridine_0',
        'Val_0',
        'Zn_0',
        'DO',
        'pH',
        'feed vol'
    ],

    4: [
        'Ala_NSRC',
        'Arg_NSRC',
        'Asn_NSRC',
        'Asp_NSRC',
        'Gln_NSRC',
        'Glu_NSRC',
        'Gly_NSRC',
        'Gly-Tyr_NSRC',
        'His_NSRC',
        'HyPro_NSRC',
        'Ile_NSRC',
        'Leu_NSRC',
        'Lys_NSRC',
        'Met_NSRC',
        'Orn_NSRC',
        'Phe_NSRC',
        'Pro_NSRC',
        'Ser_NSRC',
        'Tau_NSRC',
        'Thr_NSRC',
        'Trp_NSRC',
        'Tyr_NSRC',
        'Val_NSRC',
        'Choline_NSRC',
        'Thiamin_NSRC',
        'Pyridoxal_NSRC',
        'Pyridoxine_NSRC',
        'Nicotinamide_NSRC',
        'Pantothenic  acid_NSRC',
        'Folic acid_NSRC',
        'Cyanocobalamin_NSRC',
        'Riboflavin_NSRC',
        'Biotin_NSRC',
        'Na_NSRC',
        'Mg_NSRC',
        'P_NSRC',
        'K_NSRC',
        'Ca_NSRC',
        'Fe_NSRC',
        'Co_NSRC',
        'Cu_NSRC',
        'Zn_NSRC',
        'Mn_NSRC',
        'Ethanolamine_NSRC',
        'Putrescine_NSRC',
        'Uridine_NSRC',
        'Adenosine_NSRC',
        'DO',
        'pH',
        'feed vol'
    ]
}

xvar_list_dict = {
    1: ['Arg_basal',
        'Asn_basal',
        'Asp_basal',
        'Glu_basal',
        'His_basal',
        'Ile_basal',
        'Leu_basal',
        'Lys_basal',
        'Met_basal',
        'Orn_basal',
        'Phe_basal',
        'Pro_basal',
        'Ser_basal',
        'Thr_basal',
        'Trp_basal',
        'Tyr_basal',
        'Val_basal',
        'Choline_basal',
        'Pyridoxine_basal',
        'Nicotinamide_basal',
        'Pantothenic  acid_basal',
        'Folic acid_basal',
        'Cyanocobalamin_basal',
        'Riboflavin_basal',
        'Biotin_basal',
        'Ethanolamine_basal',
        'Uridine_basal',
        'Na_basal',
        'Mg_basal',
        'P_basal',
        'K_basal',
        'Ca_basal',
        'Fe_basal',
        'Co_basal',
        'Cu_basal',
        'Zn_basal',
        'D-glucose_basal',
        'Arg_feed',
        'Asn_feed',
        'Asp_feed',
        'Glu_feed',
        'Gly-Tyr_feed',
        'His_feed',
        'Ile_feed',
        'Leu_feed',
        'Lys_feed',
        'Met_feed',
        'Phe_feed',
        'Pro_feed',
        'Ser_feed',
        'Thr_feed',
        'Trp_feed',
        'Val_feed',
        'Choline_feed',
        'Pyridoxine_feed',
        'Nicotinamide_feed',
        'Pantothenic  acid_feed',
        'Folic acid_feed',
        'Cyanocobalamin_feed',
        'Riboflavin_feed',
        'Biotin_feed',
        'Uridine_feed',
        'Na_feed',
        'Mg_feed',
        'P_feed',
        'K_feed',
        'Ca_feed',
        'Fe_feed',
        'Co_feed',
        'Cu_feed',
        'Zn_feed',
        'Mn_feed',
        'D-glucose_feed',
        'DO',
        'pH',
        'feed vol'
        ],

    4: [
        'Arg_NSRC',
        'Asn_NSRC',
        'Asp_NSRC',
        'Glu_NSRC',
        'Gly-Tyr_NSRC',
        'His_NSRC',
        'Ile_NSRC',
        'Leu_NSRC',
        'Lys_NSRC',
        'Met_NSRC',
        'Phe_NSRC',
        'Pro_NSRC',
        'Ser_NSRC',
        'Thr_NSRC',
        'Trp_NSRC',
        'Val_NSRC',
        'Choline_NSRC',
        'Pyridoxine_NSRC',
        'Nicotinamide_NSRC',
        'Pantothenic  acid_NSRC',
        'Folic acid_NSRC',
        'Cyanocobalamin_NSRC',
        'Riboflavin_NSRC',
        'Biotin_NSRC',
        'Na_NSRC',
        'Mg_NSRC',
        'P_NSRC',
        'K_NSRC',
        'Ca_NSRC',
        'Fe_NSRC',
        'Co_NSRC',
        'Cu_NSRC',
        'Zn_NSRC',
        'Uridine_NSRC',
        'DO',
        'pH',
        'feed vol'
    ]
}

# %%
yvar_sublist_sets = [
    ['Titer (mg/L)_14', 'mannosylation_14',
     'fucosylation_14', 'galactosylation_14'],
    ['G0_14', 'G0F_14', 'G1_14', 'G1Fa_14'],
    ['G1Fb_14', 'G2_14', 'G2F_14', 'Other_14']
]

yvar_list_key = ['Titer (mg/L)_14', 'mannosylation_14',
                 'fucosylation_14', 'galactosylation_14']

process_features = ['DO', 'pH', 'feed vol']
features_selected_dict = {
    'Titer (mg/L)_14': [
        'Thr_feed',
        'Co_feed',
        'His_feed',
        'Riboflavin_feed',
        'Pro_feed',
        'K_feed',
        'Asp_feed',
        'Nicotinamide_feed',
        'Choline_feed',
        'Fe_feed']+process_features,
        
     'mannosylation_14': [
         'Riboflavin_feed',
        'Riboflavin_basal',
        'Lys_basal',
        'Ca_feed',
        'P_feed',
        'Asp_basal',
        'Uridine_feed',
        'Gly-Tyr_feed',
        'Trp_basal',
        'Folic acid_basal']+process_features,
     
     'fucosylation_14': [
         'Riboflavin_feed',
        'Riboflavin_basal',
        'Nicotinamide_basal',
        'Ca_feed',
        'Folic acid_basal',
        'Thr_feed',
        'Cu_feed',
        'Lys_basal',
        'Arg_feed',
        'Asn_feed']+process_features,
     
     'galactosylation_14': [
        'Asp_basal',
        'Co_basal',
        'Ser_basal',
        'Thr_basal',
        'Folic acid_basal',
        'Pro_feed',
        'Trp_basal',
        'Choline_feed',
        'Met_basal',
        'Nicotinamide_basal']+process_features
 }


# %% MODEL PARAMETERS

model_cmap = {'randomforest': 'r', 'plsr': 'b', 'lasso': 'g'}

model_params = {
    'X1Y0': {
        'randomforest': {
            'Titer (mg/L)_14': [{'model_type': 'randomforest', 'n_estimators': 100}],
            'mannosylation_14': [{'model_type': 'randomforest', 'n_estimators': 100}],
            'fucosylation_14': [{'model_type': 'randomforest', 'n_estimators': 100}],
            'galactosylation_14': [{'model_type': 'randomforest', 'n_estimators': 100}],
        },
        'plsr': {
            'Titer (mg/L)_14': [{'model_type': 'plsr', 'n_components': 10}],
            'mannosylation_14': [{'model_type': 'plsr', 'n_components': 9}],
            'fucosylation_14': [{'model_type': 'plsr', 'n_components': 8}],
            'galactosylation_14': [{'model_type': 'plsr', 'n_components': 8}],
        },
        'lasso': {
            'Titer (mg/L)_14': [{'model_type': 'lasso', 'max_iter': 50000, 'alpha': 0.005}],
            'mannosylation_14': [{'model_type': 'lasso', 'max_iter': 50000, 'alpha': 0.005}],
            'fucosylation_14': [{'model_type': 'lasso', 'max_iter': 50000, 'alpha': 0.005}],
            'galactosylation_14': [{'model_type': 'lasso', 'max_iter': 50000, 'alpha': 0.05}],
        }
    },
    'X4Y0': {
        'randomforest': {
            'Titer (mg/L)_14': [{'model_type': 'randomforest', 'n_estimators': 100}],
            'mannosylation_14': [{'model_type': 'randomforest', 'n_estimators': 100}],
            'fucosylation_14': [{'model_type': 'randomforest', 'n_estimators': 100}],
            'galactosylation_14': [{'model_type': 'randomforest', 'n_estimators': 100}],
        },
        'plsr': {
            'Titer (mg/L)_14': [{'model_type': 'plsr', 'n_components': 11}],
            'mannosylation_14': [{'model_type': 'plsr', 'n_components': 8}],
            'fucosylation_14': [{'model_type': 'plsr', 'n_components': 7}],
            'galactosylation_14': [{'model_type': 'plsr', 'n_components': 9}],
        },
        'lasso': {
            'Titer (mg/L)_14': [{'model_type': 'lasso', 'max_iter': 50000, 'alpha': 10}],
            'mannosylation_14': [{'model_type': 'lasso', 'max_iter': 50000, 'alpha': 0.05}],
            'fucosylation_14': [{'model_type': 'lasso', 'max_iter': 50000, 'alpha': 0.005}],
            'galactosylation_14': [{'model_type': 'lasso', 'max_iter': 50000, 'alpha': 0.01}],
        }
    }
    }
