#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jul 23 10:42:17 2024

@author: charmainechia
"""

def sort_list(lst):
    lst.sort()
    return lst

def dict_update(d, keyval):
    d.update(keyval)
    return d
    

var_dict_all = {
    'inputs': [
        'Basal medium',
        'Feed medium',
        'DO',
        'pH',
        'feed %',
        'feed day',
        'n'
        ],
    'VCD, VIA, Titer, metabolites': [
        'VCD (E6 cells/mL)',
        'Viability (%)',
        'Titer (mg/L)',
        'Osmolarity (mOsm/kg)',
        'Glucose (g/L)',
        'Lac (g/L)',
        'NH4+ (mM)'
        ],
    'AA': [
        'Ala',
        'Arg',
        'Asn',
        'Asp',
        'Gln',
        'Glu',
        'Gly',
        'Gly-Tyr',
        'His',
        'HyPro',
        'Ile',
        'Leu',
        'Lys',
        'Met',
        'Orn',
        'Phe',
        'Pro',
        'Ser',
        'Tau',
        'Thr',
        'Trp',
        'Tyr',
        'Val'
        ],
    'VT': [
        'Choline',
        'Thiamin',
        'Pyridoxal',
        'Pyridoxine',
        'Nicotinamide',
        'Pantothenic  acid',
        'Folic acid',
        'Cyanocobalamin',
        'Riboflavin',
        'Biotin'
        ],
    'MT': [
        'Na', 
        'Mg', 
        'P', 
        'K', 
        'Ca', 
        'Fe', 
        'Co', 
        'Cu', 
        'Zn', 
        'Mn'
        ],
    'Glyco': [
        'Man5', 
        'G0', 
        'G0F', 
        'G1', 
        'G1Fa', 
        'G1Fb', 
        'G2', 
        'G2F', 
        'Other'
        ],
    'Nuc, Amine': [
        'Ethanolamine', 
        'Putrescine', 
        'Uridine', 
        'Adenosine'
        ], 
    'media_components': [
        'Ala',
        'Arg',
        'Asn',
        'Asp',
        'Glu',
        'Gly',
        'Gly-Tyr',
        'His',
        'HyPro',
        'Ile',
        'Leu',
        'Lys',
        'Met',
        'Orn',
        'Phe',
        'Pro',
        'Ser',
        'Tau',
        'Thr',
        'Trp',
        'Tyr',
        'Val',
        'Choline',
        'Thiamin',
        'Pyridoxal',
        'Pyridoxine',
        'Nicotinamide',
        'Pantothenic  acid',
        'Folic acid',
        'Cyanocobalamin',
        'Riboflavin',
        'Biotin',
        'Na',
        'Mg',
        'P',
        'K',
        'Ca',
        'Fe',
        'Co',
        'Cu',
        'Zn',
        'Mn',
        'D-glucose'
     ]
    }

overall_glyco_cqas = {
    'mannosylation': ['Man5'],
    'fucosylation': ['G0F', 'G1Fa', 'G1Fb', 'G2F'],
    'galactosylation': ['G0', 'G0F', 'G1', 'G1Fa', 'G1Fb', 'G2', 'G2F']
    }

#%% X % Y DATASET VARIABLES
xvar_list_dict_prefilt = {
0: ['Adenosine_0',
  'Ala_0',
  'Arg_0',
  'Asn_0',
  'Asp_0',
  'Biotin_0',
  'Ca_0',
  'Choline_0',
  'Co_0',
  'Cu_0',
  'Cyanocobalamin_0',
  'Ethanolamine_0',
  'Fe_0',
  'Folic acid_0',
  'Gln_0',
  'Glu_0',
  'Glucose (g/L)_0',
  'Gly-Tyr_0',
  'Gly_0',
  'His_0',
  'HyPro_0',
  'Ile_0',
  'K_0',
  'Leu_0',
  'Lys_0',
  'Met_0',
  'Mg_0',
  'Mn_0',
  'Na_0',
  'Nicotinamide_0',
  'Orn_0',
  'P_0',
  'Pantothenic  acid_0',
  'Phe_0',
  'Pro_0',
  'Putrescine_0',
  'Pyridoxal_0',
  'Pyridoxine_0',
  'Riboflavin_0',
  'Ser_0',
  'Tau_0',
  'Thiamin_0',
  'Thr_0',
  'Trp_0',
  'Tyr_0',
  'Uridine_0',
  'Val_0',
  'Zn_0',
  'DO',
  'pH',
  'feed %'
  ],
1: ['Arg_basal',
 'Asn_basal',
 'Asp_basal',
 'Biotin_basal',
 'Ca_basal',
 'Choline_basal',
 'Co_basal',
 'Cu_basal',
 'Cyanocobalamin_basal',
 'D-glucose_basal',
 'Fe_basal',
 'Folic acid_basal',
 'Glu_basal',
 'His_basal',
 'Ile_basal',
 'K_basal',
 'Leu_basal',
 'Lys_basal',
 'Met_basal',
 'Mg_basal',
 'Na_basal',
 'Nicotinamide_basal',
 'Orn_basal',
 'P_basal',
 'Pantothenic  acid_basal',
 'Phe_basal',
 'Pro_basal',
 'Pyridoxine_basal',
 'Riboflavin_basal',
 'Ser_basal',
 'Thr_basal',
 'Trp_basal',
 'Tyr_basal',
 'Val_basal',
 'Zn_basal',
 'Arg_feed',
 'Asn_feed',
 'Asp_feed',
 'Biotin_feed',
 'Ca_feed',
 'Choline_feed',
 'Co_feed',
 'Cu_feed',
 'Cyanocobalamin_feed',
 'D-glucose_feed',
 'Fe_feed',
 'Folic acid_feed',
 'Glu_feed',
 'Gly-Tyr_feed',
 'His_feed',
 'Ile_feed',
 'K_feed',
 'Leu_feed',
 'Lys_feed',
 'Met_feed',
 'Mg_feed',
 'Mn_feed',
 'Na_feed',
 'Nicotinamide_feed',
 'P_feed',
 'Pantothenic  acid_feed',
 'Phe_feed',
 'Pro_feed',
 'Pyridoxine_feed',
 'Riboflavin_feed',
 'Ser_feed',
 'Thr_feed',
 'Trp_feed',
 'Val_feed',
 'Zn_feed',
 'DO',
 'pH',
 'feed %'
 ]
}

#%%

xvar_list_dict = {
0: ['Ala_0',
 'Arg_0',
 'Asn_0',
 'Asp_0',
 'Biotin_0',
 'Ca_0',
 'Choline_0',
 'Co_0',
 'Cu_0',
 'Cyanocobalamin_0',
 'Ethanolamine_0',
 'Fe_0',
 'Folic acid_0',
 'Gln_0',
 'Glu_0',
 'Glucose (g/L)_0',
 'Gly_0',
 'His_0',
 'HyPro_0',
 'Ile_0',
 'K_0',
 'Leu_0',
 'Lys_0',
 'Met_0',
 'Mg_0',
 'Mn_0',
 'Na_0',
 'Nicotinamide_0',
 'Orn_0',
 'P_0',
 'Pantothenic  acid_0',
 'Phe_0',
 'Pro_0',
 'Pyridoxal_0',
 'Pyridoxine_0',
 'Riboflavin_0',
 'Ser_0',
 'Tau_0',
 'Thr_0',
 'Trp_0',
 'Tyr_0',
 'Val_0',
 'Zn_0',
 'DO',
 'pH',
 'feed %'
 ],

1: ['Arg_basal',
 'Asn_basal',
 'Asp_basal',
 'Biotin_basal',
 'Ca_basal',
 'Choline_basal',
 'Co_basal',
 'Cu_basal',
 'Cyanocobalamin_basal',
 'D-glucose_basal',
 'Fe_basal',
 'Folic acid_basal',
 'Glu_basal',
 'His_basal',
 'Ile_basal',
 'K_basal',
 'Leu_basal',
 'Lys_basal',
 'Met_basal',
 'Mg_basal',
 'Na_basal',
 'Nicotinamide_basal',
 'Orn_basal',
 'P_basal',
 'Pantothenic  acid_basal',
 'Phe_basal',
 'Pro_basal',
 'Pyridoxine_basal',
 'Riboflavin_basal',
 'Ser_basal',
 'Thr_basal',
 'Trp_basal',
 'Tyr_basal',
 'Val_basal',
 'Zn_basal',
 'Arg_feed',
 'Asn_feed',
 'Asp_feed',
 'Biotin_feed',
 'Ca_feed',
 'Choline_feed',
 'Co_feed',
 'Cu_feed',
 'Cyanocobalamin_feed',
 'D-glucose_feed',
 'Fe_feed',
 'Folic acid_feed',
 'Glu_feed',
 'Gly-Tyr_feed',
 'His_feed',
 'Ile_feed',
 'K_feed',
 'Leu_feed',
 'Lys_feed',
 'Met_feed',
 'Mg_feed',
 'Mn_feed',
 'Na_feed',
 'Nicotinamide_feed',
 'P_feed',
 'Pantothenic  acid_feed',
 'Phe_feed',
 'Pro_feed',
 'Pyridoxine_feed',
 'Riboflavin_feed',
 'Ser_feed',
 'Thr_feed',
 'Trp_feed',
 'Val_feed',
 'Zn_feed',
 'DO',
 'pH',
 'feed %'
 ]
    }


yvar_list_dict = {
0: ['Titer (mg/L)_14',
    'mannosylation_14',
    'fucosylation_14',
    'galactosylation_14',
    'G0_14',
    'G0F_14',
    'G1_14',
    'G1Fa_14',
    'G1Fb_14',
    'G2_14',
    'G2F_14',
    'Other_14'
    ],
    }


yvar_sublist_sets = [
    ['Titer (mg/L)_14', 'mannosylation_14', 'fucosylation_14', 'galactosylation_14'], 
    ['G0_14', 'G0F_14', 'G1_14', 'G1Fa_14'],
    ['G1Fb_14', 'G2_14', 'G2F_14', 'Other_14']
    ]

common_xvars_dict = {
    (0,1): ['Arg',
     'Asn',
     'Asp',
     'Biotin',
     'Ca',
     'Choline',
     'Co',
     'Cu',
     'Cyanocobalamin',
     'Fe',
     'Folic acid',
     'Glu',
     'His',
     'Ile',
     'K',
     'Leu',
     'Lys',
     'Met',
     'Mg',
     'Na',
     'Nicotinamide',
     'Orn',
     'P',
     'Pantothenic  acid',
     'Phe',
     'Pro',
     'Pyridoxine',
     'Riboflavin',
     'Ser',
     'Thr',
     'Trp',
     'Tyr',
     'Val',
     'Zn']
    }

#%% MODEL PARAMETERS

model_params = {
'X0Y0':{
'randomforest': {
    'Titer (mg/L)_14': [{'model_type': 'randomforest', 'n_estimators': 40}],
    'mannosylation_14': [{'model_type': 'randomforest', 'n_estimators': 140}],
    'fucosylation_14': [{'model_type': 'randomforest', 'n_estimators': 140}],
    'galactosylation_14': [{'model_type': 'randomforest', 'n_estimators': 60}],
    'G0_14': [{'model_type': 'randomforest', 'n_estimators': 120}],
    'G0F_14': [{'model_type': 'randomforest', 'n_estimators': 80}],
    'G1_14': [{'model_type': 'randomforest', 'n_estimators': 180}],
    'G1Fa_14': [{'model_type': 'randomforest', 'n_estimators': 140}],
    'G1Fb_14': [{'model_type': 'randomforest', 'n_estimators': 140}],
    'G2_14': [{'model_type': 'randomforest', 'n_estimators': 180}],
    'G2F_14': [{'model_type': 'randomforest', 'n_estimators': 180}],
    'Other_14': [{'model_type': 'randomforest', 'n_estimators': 180}]    
    },
'plsr' : {
    'Titer (mg/L)_14': [{'model_type': 'plsr', 'n_components':4}],
    'mannosylation_14': [{'model_type': 'plsr', 'n_components':10}],
    'fucosylation_14': [{'model_type': 'plsr', 'n_components':10}],
    'galactosylation_14': [{'model_type': 'plsr', 'n_components':10}],
    'G0_14': [{'model_type': 'plsr', 'n_components':9}],
    'G0F_14': [{'model_type': 'plsr', 'n_components':8}],
    'G1_14': [{'model_type': 'plsr', 'n_components':10}],
    'G1Fa_14': [{'model_type': 'plsr', 'n_components':4}],
    'G1Fb_14': [{'model_type': 'plsr', 'n_components':4}],
    'G2_14': [{'model_type': 'plsr', 'n_components':8}],
    'G2F_14': [{'model_type': 'plsr', 'n_components':9}],
    'Other_14': [{'model_type': 'plsr', 'n_components':10}]
    },
'lasso': {
    'Titer (mg/L)_14': [{'model_type': 'lasso', 'max_iter':50000, 'alpha':100}],
    'mannosylation_14': [{'model_type': 'lasso', 'max_iter':50000, 'alpha':0.1}],
    'fucosylation_14': [{'model_type': 'lasso', 'max_iter':50000, 'alpha':0.1}],
    'galactosylation_14': [{'model_type': 'lasso', 'max_iter':50000, 'alpha':0.1}],
    'G0_14': [{'model_type': 'lasso', 'max_iter':50000, 'alpha':0.05}],
    'G0F_14': [{'model_type': 'lasso', 'max_iter':50000, 'alpha':0.005}],
    'G1_14': [{'model_type': 'lasso', 'max_iter':50000, 'alpha':0.01}],
    'G1Fa_14': [{'model_type': 'lasso', 'max_iter':50000, 'alpha':0.05}],
    'G1Fb_14': [{'model_type': 'lasso', 'max_iter':50000, 'alpha':0.05}],
    'G2_14': [{'model_type': 'lasso', 'max_iter':50000, 'alpha':0.01}],
    'G2F_14': [{'model_type': 'lasso', 'max_iter':50000, 'alpha':0.01}],
    'Other_14': [{'model_type': 'lasso', 'max_iter':50000, 'alpha':0.05}]     
    }
},

'X1Y0':{
'randomforest': {
    'Titer (mg/L)_14': [{'model_type': 'randomforest', 'n_estimators': 60}],
    'mannosylation_14': [{'model_type': 'randomforest', 'n_estimators': 160}],
    'fucosylation_14': [{'model_type': 'randomforest', 'n_estimators': 100}],
    'galactosylation_14': [{'model_type': 'randomforest', 'n_estimators': 160}],
    'G0_14': [{'model_type': 'randomforest', 'n_estimators': 20}],
    'G0F_14': [{'model_type': 'randomforest', 'n_estimators': 80}],
    'G1_14': [{'model_type': 'randomforest', 'n_estimators': 40}],
    'G1Fa_14': [{'model_type': 'randomforest', 'n_estimators': 180}],
    'G1Fb_14': [{'model_type': 'randomforest', 'n_estimators': 80}],
    'G2_14': [{'model_type': 'randomforest', 'n_estimators': 140}],
    'G2F_14': [{'model_type': 'randomforest', 'n_estimators': 120}],
    'Other_14': [{'model_type': 'randomforest', 'n_estimators': 20}]    
    },
'plsr' : {
    'Titer (mg/L)_14': [{'model_type': 'plsr', 'n_components':5}],
    'mannosylation_14': [{'model_type': 'plsr', 'n_components':7}],
    'fucosylation_14': [{'model_type': 'plsr', 'n_components':7}],
    'galactosylation_14': [{'model_type': 'plsr', 'n_components':8}],
    'G0_14': [{'model_type': 'plsr', 'n_components':6}],
    'G0F_14': [{'model_type': 'plsr', 'n_components':7}],
    'G1_14': [{'model_type': 'plsr', 'n_components':4}],
    'G1Fa_14': [{'model_type': 'plsr', 'n_components':8}],
    'G1Fb_14': [{'model_type': 'plsr', 'n_components':7}],
    'G2_14': [{'model_type': 'plsr', 'n_components':7}],
    'G2F_14': [{'model_type': 'plsr', 'n_components':8}],
    'Other_14': [{'model_type': 'plsr', 'n_components':5}]
    },
'lasso': {
    'Titer (mg/L)_14': [{'model_type': 'lasso', 'max_iter':50000, 'alpha':20}],
    'mannosylation_14': [{'model_type': 'lasso', 'max_iter':50000, 'alpha':0.1}],
    'fucosylation_14': [{'model_type': 'lasso', 'max_iter':50000, 'alpha':0.1}],
    'galactosylation_14': [{'model_type': 'lasso', 'max_iter':50000, 'alpha':0.1}],
    'G0_14': [{'model_type': 'lasso', 'max_iter':50000, 'alpha':0.01}],
    'G0F_14': [{'model_type': 'lasso', 'max_iter':50000, 'alpha':0.05}],
    'G1_14': [{'model_type': 'lasso', 'max_iter':50000, 'alpha':0.05}],
    'G1Fa_14': [{'model_type': 'lasso', 'max_iter':50000, 'alpha':0.1}],
    'G1Fb_14': [{'model_type': 'lasso', 'max_iter':50000, 'alpha':0.01}],
    'G2_14': [{'model_type': 'lasso', 'max_iter':50000, 'alpha':0.01}],
    'G2F_14': [{'model_type': 'lasso', 'max_iter':50000, 'alpha':0.01}],
    'Other_14': [{'model_type': 'lasso', 'max_iter':50000, 'alpha':0.05}]     
    }
},
'X1Y0_subset1':{
'randomforest': {
    'Titer (mg/L)_14': [{'model_type': 'randomforest', 'n_estimators': 100, 'f':0.2}],
    'mannosylation_14': [{'model_type': 'randomforest', 'n_estimators': 100, 'f':0.1}],
    'fucosylation_14': [{'model_type': 'randomforest', 'n_estimators': 100, 'f':0.1}],
    'galactosylation_14': [{'model_type': 'randomforest', 'n_estimators': 100, 'f':0.1}],
    'G0_14': [{'model_type': 'randomforest', 'n_estimators': 100, 'f':0.4}],
    'G0F_14': [{'model_type': 'randomforest', 'n_estimators': 100, 'f':0.5}],
    'G1_14': [{'model_type': 'randomforest', 'n_estimators': 100, 'f':0.5}],
    'G1Fa_14': [{'model_type': 'randomforest', 'n_estimators': 100, 'f':0.05}],
    'G1Fb_14': [{'model_type': 'randomforest', 'n_estimators': 100, 'f':0.1}],
    'G2_14': [{'model_type': 'randomforest', 'n_estimators': 100, 'f':0.1}],
    'G2F_14': [{'model_type': 'randomforest', 'n_estimators': 100, 'f':0.8}],
    'Other_14': [{'model_type': 'randomforest', 'n_estimators': 100, 'f':0.1}]    
    }
},
'X0Y0_subset2':{
'randomforest': {
    'Titer (mg/L)_14': [{'model_type': 'randomforest', 'n_estimators': 100, 'f':0.4}],
    'mannosylation_14': [{'model_type': 'randomforest', 'n_estimators': 100, 'f':0.3}],
    'fucosylation_14': [{'model_type': 'randomforest', 'n_estimators': 100, 'f':0.2}],
    'galactosylation_14': [{'model_type': 'randomforest', 'n_estimators': 100, 'f':0.2}],
    'G0_14': [{'model_type': 'randomforest', 'n_estimators': 100, 'f':0.1}],
    'G0F_14': [{'model_type': 'randomforest', 'n_estimators': 100, 'f':0.05}],
    'G1_14': [{'model_type': 'randomforest', 'n_estimators': 100, 'f':0.1}],
    'G1Fa_14': [{'model_type': 'randomforest', 'n_estimators': 100, 'f':0.1}],
    'G1Fb_14': [{'model_type': 'randomforest', 'n_estimators': 100, 'f':0.1}],
    'G2_14': [{'model_type': 'randomforest', 'n_estimators': 100, 'f':0.2}],
    'G2F_14': [{'model_type': 'randomforest', 'n_estimators': 100, 'f':0.05}],
    'Other_14': [{'model_type': 'randomforest', 'n_estimators': 100, 'f':0.1}]    
    }
}
}

